# Generated by Django 3.1.7 on 2022-06-17 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboards',
            name='Have',
            field=models.CharField(choices=[('Academic problems', 'Academic problems'), ('Agricultural problems', 'Agricultural problems'), ('Adventure problems', 'Adventure problems'), ('Anxiety problems', 'Anxiety problems'), ('Business problems', 'Business problems'), ('Biological problems', 'Biological problems'), ('Chemical problems', 'Chemical problems'), ('Ceremonic problems', 'Ceremonic problems'), ('Confidential problems', 'Confidential problems'), ('Climentic problems', 'Climentic problems'), ('Depression problems', 'Depression problems'), ('Developmental problems', 'Developmental problems'), ('Entertainment problems', 'Entertainment problems'), ('Emotional problems', 'Emotional problems'), ('Environmental problems', 'Environmental problems'), ('Fashion and Design problems', 'Fashion and Design problems'), ('Financial problems', 'Financial problems'), ('Friendship problems', 'Friendship problems'), ('Freedom problems', 'Freedom problems'), ('Health problems', 'Health problems'), ('Love and Relationship problems', 'Love and Relationship problems'), ('Medical problems', 'Medical problems'), ('Mental problems', 'Mental problems'), ('Parental problems', 'Parental problems'), ('Political problems', 'Political problems'), ('Religious problems', 'Religious problems'), ('Research and Discovery problems', 'Research and Discovery problems'), ('Stress problems', 'Stress problems'), ('Shopping problems', 'Shopping problems'), ('Security problems', 'Security problems'), ('Self Defence problems', 'Self Defence problems'), ('Self Esteem problems', 'Self Esteem problems'), ('Self Care problems', 'Self Care problems'), ('Self Control problems', 'Self Control problems'), ('Sports problems', 'Sports problems'), ('Talental problems', 'Talental problems'), ('Technological problems', 'Technological problems'), ('Traditional problems', 'Traditional problems'), ('Travel problems', 'Travel problems'), ('Other problems', 'Other problems')], max_length=1000),
        ),
    ]
